# Python Clickjacking Protection with Django.
# The clickjacking middleware and decorators provide easy-to-use protection against clickjacking.
# This type of attack occurs when a malicious site tricks a user into clicking on a concealed element of another site which they have loaded
# in a hidden frame or iframe.
#

#
# Setting X-Frame-Options for all responses.
# To set the same X-Frame-Options value for all responses in your site, put 'django.middleware.
# clickjacking.XFrameOptionsMiddleware' to MIDDLEWARE:

MIDDLEWARE = [

# ...

'django.middleware.clickjacking.XFrameOptionsMiddleware',

# ...

]

#
# This middleware is enabled in the settings file generated by startproject.
# By default, the middleware will set the X-Frame-Options header to SAMEORIGIN for every outgoing HttpResponse.
# If you want DENY instead, set the X_FRAME_OPTIONS setting:
#

X_FRAME_OPTIONS = 'DENY'
